spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/university_db?useSSL=false&serverTimezone=UTC
    password: ''
  application:
    name: simple-api
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: '8082'
greeting:
  message: Hello World!
