server:
  port: 9001

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration?useSSL=false&serverTimezone=UTC
    username: root
    password:
